// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SWLOR.Web.Data.Entities.Data.Entities
{
    public partial class BankItem
    {
        public string ID { get; set; }
        public int BankID { get; set; }
        public string PlayerID { get; set; }
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public string ItemTag { get; set; }
        public string ItemResref { get; set; }
        public string ItemObject { get; set; }
        public DateTime DateStored { get; set; }
        public int ClusterID { get; set; }

        public virtual Bank Bank { get; set; }
        public virtual Player Player { get; set; }
    }
}