// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SWLOR.Web.Data.Entities.Data.Entities
{
    public partial class BugReport
    {
        public string ID { get; set; }
        public string SenderPlayerID { get; set; }
        public string CDKey { get; set; }
        public string Text { get; set; }
        public string TargetName { get; set; }
        public string AreaResref { get; set; }
        public double SenderLocationX { get; set; }
        public double SenderLocationY { get; set; }
        public double SenderLocationZ { get; set; }
        public double SenderLocationOrientation { get; set; }
        public DateTime DateSubmitted { get; set; }
        public int ClusterID { get; set; }

        public virtual Player SenderPlayer { get; set; }
    }
}