// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SWLOR.Web.Data.Entities.Data.Entities
{
    public partial class ChatLog
    {
        public string ID { get; set; }
        public int ChatChannelID { get; set; }
        public string SenderPlayerID { get; set; }
        public string SenderAccountName { get; set; }
        public string SenderCDKey { get; set; }
        public string ReceiverPlayerID { get; set; }
        public string ReceiverAccountName { get; set; }
        public string ReceiverCDKey { get; set; }
        public string Message { get; set; }
        public DateTime DateSent { get; set; }
        public string SenderDMName { get; set; }
        public string ReceiverDMName { get; set; }
        public int ClusterID { get; set; }

        public virtual ChatChannel ChatChannel { get; set; }
        public virtual Player ReceiverPlayer { get; set; }
        public virtual Player SenderPlayer { get; set; }
    }
}