// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SWLOR.Web.Data.Entities.Data.Entities
{
    public partial class DMAction
    {
        public string ID { get; set; }
        public int DMActionTypeID { get; set; }
        public string Name { get; set; }
        public string CDKey { get; set; }
        public DateTime DateOfAction { get; set; }
        public string Details { get; set; }
        public int ClusterID { get; set; }

        public virtual DMActionType DMActionType { get; set; }
    }
}