// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SWLOR.Web.Data.Entities.Data.Entities
{
    public partial class Error
    {
        public string ID { get; set; }
        public DateTime DateCreated { get; set; }
        public string Message { get; set; }
        public string StackTrace { get; set; }
        public string Caller { get; set; }
        public int ClusterID { get; set; }
    }
}