// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SWLOR.Web.Data.Entities.Data.Entities
{
    public partial class Guild
    {
        public Guild()
        {
            GuildTask = new HashSet<GuildTask>();
            PCGuildPoint = new HashSet<PCGuildPoint>();
        }

        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public virtual ICollection<GuildTask> GuildTask { get; set; }
        public virtual ICollection<PCGuildPoint> PCGuildPoint { get; set; }
    }
}