// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SWLOR.Web.Data.Entities.Data.Entities
{
    public partial class GuildTask
    {
        public int ID { get; set; }
        public int GuildID { get; set; }
        public int QuestID { get; set; }
        public int RequiredRank { get; set; }
        public bool IsCurrentlyOffered { get; set; }

        public virtual Guild Guild { get; set; }
    }
}