// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SWLOR.Web.Data.Entities.Data.Entities
{
    public partial class Message
    {
        public string ID { get; set; }
        public string BoardID { get; set; }
        public string PlayerID { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public DateTime DatePosted { get; set; }
        public DateTime DateExpires { get; set; }
        public DateTime? DateRemoved { get; set; }
        public int ClusterID { get; set; }

        public virtual Player Player { get; set; }
    }
}