// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SWLOR.Web.Data.Entities.Data.Entities
{
    public partial class PCCooldown
    {
        public string ID { get; set; }
        public string PlayerID { get; set; }
        public int CooldownCategoryID { get; set; }
        public DateTime DateUnlocked { get; set; }
        public int ClusterID { get; set; }

        public virtual CooldownCategory CooldownCategory { get; set; }
        public virtual Player Player { get; set; }
    }
}