// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SWLOR.Web.Data.Entities.Data.Entities
{
    public partial class PCCraftedBlueprint
    {
        public string ID { get; set; }
        public string PlayerID { get; set; }
        public int CraftBlueprintID { get; set; }
        public DateTime DateFirstCrafted { get; set; }
        public int ClusterID { get; set; }

        public virtual CraftBlueprint CraftBlueprint { get; set; }
        public virtual Player Player { get; set; }
    }
}