// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SWLOR.Web.Data.Entities.Data.Entities
{
    public partial class PCGuildPoint
    {
        public string ID { get; set; }
        public string PlayerID { get; set; }
        public int GuildID { get; set; }
        public int Rank { get; set; }
        public int Points { get; set; }

        public virtual Guild Guild { get; set; }
        public virtual Player Player { get; set; }
    }
}