// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SWLOR.Web.Data.Entities.Data.Entities
{
    public partial class PCHelmet
    {
        public string PlayerID { get; set; }
        public string Helmet1 { get; set; }
        public string Helmet2 { get; set; }
        public string Helmet3 { get; set; }
        public string Helmet4 { get; set; }
        public string Helmet5 { get; set; }
        public string Helmet6 { get; set; }
        public string Helmet7 { get; set; }
        public string Helmet8 { get; set; }
        public string Helmet9 { get; set; }
        public string Helmet10 { get; set; }
        public int ClusterID { get; set; }

        public virtual Player Player { get; set; }
    }
}