// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SWLOR.Web.Data.Entities.Data.Entities
{
    public partial class PCPerk
    {
        public string ID { get; set; }
        public string PlayerID { get; set; }
        public DateTime AcquiredDate { get; set; }
        public int PerkID { get; set; }
        public int PerkLevel { get; set; }
        public int ClusterID { get; set; }

        public virtual Perk Perk { get; set; }
        public virtual Player Player { get; set; }
    }
}