// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SWLOR.Web.Data.Entities.Data.Entities
{
    public partial class PCQuestKillTargetProgress
    {
        public string ID { get; set; }
        public string PlayerID { get; set; }
        public string PCQuestStatusID { get; set; }
        public int NPCGroupID { get; set; }
        public int RemainingToKill { get; set; }
        public int ClusterID { get; set; }

        public virtual NPCGroup NPCGroup { get; set; }
        public virtual PCQuestStatus PCQuestStatus { get; set; }
        public virtual Player Player { get; set; }
    }
}