// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SWLOR.Web.Data.Entities.Data.Entities
{
    public partial class PCQuestStatus
    {
        public PCQuestStatus()
        {
            PCQuestItemProgress = new HashSet<PCQuestItemProgress>();
            PCQuestKillTargetProgress = new HashSet<PCQuestKillTargetProgress>();
        }

        public string ID { get; set; }
        public string PlayerID { get; set; }
        public int QuestID { get; set; }
        public DateTime? CompletionDate { get; set; }
        public int? SelectedItemRewardID { get; set; }
        public int ClusterID { get; set; }
        public int TimesCompleted { get; set; }
        public int QuestState { get; set; }

        public virtual Player Player { get; set; }
        public virtual ICollection<PCQuestItemProgress> PCQuestItemProgress { get; set; }
        public virtual ICollection<PCQuestKillTargetProgress> PCQuestKillTargetProgress { get; set; }
    }
}