// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SWLOR.Web.Data.Entities.Data.Entities
{
    public partial class PCRegionalFame
    {
        public string ID { get; set; }
        public string PlayerID { get; set; }
        public int FameRegionID { get; set; }
        public int Amount { get; set; }
        public int ClusterID { get; set; }

        public virtual FameRegion FameRegion { get; set; }
        public virtual Player Player { get; set; }
    }
}