// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SWLOR.Web.Data.Entities.Data.Entities
{
    public partial class PCWeapon
    {
        public string PlayerID { get; set; }
        public string Weapon1 { get; set; }
        public string Weapon2 { get; set; }
        public string Weapon3 { get; set; }
        public string Weapon4 { get; set; }
        public string Weapon5 { get; set; }
        public string Weapon6 { get; set; }
        public string Weapon7 { get; set; }
        public string Weapon8 { get; set; }
        public string Weapon9 { get; set; }
        public string Weapon10 { get; set; }
        public int ClusterID { get; set; }

        public virtual Player Player { get; set; }
    }
}