// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SWLOR.Web.Data.Entities.Data.Entities
{
    public partial class Starport
    {
        public int ID { get; set; }
        public string StarportID { get; set; }
        public string PlanetName { get; set; }
        public string Name { get; set; }
        public int CustomsDC { get; set; }
        public int Cost { get; set; }
        public string WaypointTag { get; set; }
    }
}